package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsItmRtlStrId generated by hbm2java
 */
@Embeddable
public class AsItmRtlStrId implements java.io.Serializable {

	private String idItm;
	private String idStrRt;

	public AsItmRtlStrId() {
	}

	public AsItmRtlStrId(String idItm, String idStrRt) {
		this.idItm = idItm;
		this.idStrRt = idStrRt;
	}

	@Column(name = "ID_ITM", nullable = false, length = 14)
	public String getIdItm() {
		return this.idItm;
	}

	public void setIdItm(String idItm) {
		this.idItm = idItm;
	}

	@Column(name = "ID_STR_RT", nullable = false, length = 5)
	public String getIdStrRt() {
		return this.idStrRt;
	}

	public void setIdStrRt(String idStrRt) {
		this.idStrRt = idStrRt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsItmRtlStrId))
			return false;
		AsItmRtlStrId castOther = (AsItmRtlStrId) other;

		return ((this.getIdItm() == castOther.getIdItm()) || (this.getIdItm() != null
				&& castOther.getIdItm() != null && this.getIdItm().equals(
				castOther.getIdItm())))
				&& ((this.getIdStrRt() == castOther.getIdStrRt()) || (this
						.getIdStrRt() != null && castOther.getIdStrRt() != null && this
						.getIdStrRt().equals(castOther.getIdStrRt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdItm() == null ? 0 : this.getIdItm().hashCode());
		result = 37 * result
				+ (getIdStrRt() == null ? 0 : this.getIdStrRt().hashCode());
		return result;
	}

}
