package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsItmRtlStr generated by hbm2java
 */
@Entity
@Table(name = "AS_ITM_RTL_STR")
public class AsItmRtlStr implements java.io.Serializable {

	private AsItmRtlStrId id;
	private Character flStkUptOnHd;
	private Date dcItmSls;
	private String scItmSls;
	private BigDecimal rpPrcCmprAtSls;
	private Date dcPrcMfRecRt;
	private BigDecimal rpPrcMfRecRt;
	private BigDecimal idGpTx;
	private Date dcPrcSlsEpCrt;
	private Date dcPrcSlsEfCrt;
	private Character flPrcRtPntAlw;
	private String tyPrcRt;
	private BigDecimal rpSlsCrt;
	private Date dcPrcEfPrnRt;
	private BigDecimal quMkdPrPrcPr;
	private Character flMkdOrglPrcPr;
	private BigDecimal rpPrSls;
	private String scItm;
	private BigDecimal idnSlsAgRst;
	private String idTmpltLb;
	private Serializable tsCrtRcrd;
	private Serializable tsMdfRcrd;
	private String sslBizFrmt;
	private String prcMxmRt;

	public AsItmRtlStr() {
	}

	public AsItmRtlStr(AsItmRtlStrId id, BigDecimal idnSlsAgRst) {
		this.id = id;
		this.idnSlsAgRst = idnSlsAgRst;
	}

	public AsItmRtlStr(AsItmRtlStrId id, Character flStkUptOnHd, Date dcItmSls,
			String scItmSls, BigDecimal rpPrcCmprAtSls, Date dcPrcMfRecRt,
			BigDecimal rpPrcMfRecRt, BigDecimal idGpTx, Date dcPrcSlsEpCrt,
			Date dcPrcSlsEfCrt, Character flPrcRtPntAlw, String tyPrcRt,
			BigDecimal rpSlsCrt, Date dcPrcEfPrnRt, BigDecimal quMkdPrPrcPr,
			Character flMkdOrglPrcPr, BigDecimal rpPrSls, String scItm,
			BigDecimal idnSlsAgRst, String idTmpltLb, Serializable tsCrtRcrd,
			Serializable tsMdfRcrd, String sslBizFrmt, String prcMxmRt) {
		this.id = id;
		this.flStkUptOnHd = flStkUptOnHd;
		this.dcItmSls = dcItmSls;
		this.scItmSls = scItmSls;
		this.rpPrcCmprAtSls = rpPrcCmprAtSls;
		this.dcPrcMfRecRt = dcPrcMfRecRt;
		this.rpPrcMfRecRt = rpPrcMfRecRt;
		this.idGpTx = idGpTx;
		this.dcPrcSlsEpCrt = dcPrcSlsEpCrt;
		this.dcPrcSlsEfCrt = dcPrcSlsEfCrt;
		this.flPrcRtPntAlw = flPrcRtPntAlw;
		this.tyPrcRt = tyPrcRt;
		this.rpSlsCrt = rpSlsCrt;
		this.dcPrcEfPrnRt = dcPrcEfPrnRt;
		this.quMkdPrPrcPr = quMkdPrPrcPr;
		this.flMkdOrglPrcPr = flMkdOrglPrcPr;
		this.rpPrSls = rpPrSls;
		this.scItm = scItm;
		this.idnSlsAgRst = idnSlsAgRst;
		this.idTmpltLb = idTmpltLb;
		this.tsCrtRcrd = tsCrtRcrd;
		this.tsMdfRcrd = tsMdfRcrd;
		this.sslBizFrmt = sslBizFrmt;
		this.prcMxmRt = prcMxmRt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idItm", column = @Column(name = "ID_ITM", nullable = false, length = 14)),
			@AttributeOverride(name = "idStrRt", column = @Column(name = "ID_STR_RT", nullable = false, length = 5)) })
	public AsItmRtlStrId getId() {
		return this.id;
	}

	public void setId(AsItmRtlStrId id) {
		this.id = id;
	}

	@Column(name = "FL_STK_UPT_ON_HD", length = 1)
	public Character getFlStkUptOnHd() {
		return this.flStkUptOnHd;
	}

	public void setFlStkUptOnHd(Character flStkUptOnHd) {
		this.flStkUptOnHd = flStkUptOnHd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DC_ITM_SLS", length = 7)
	public Date getDcItmSls() {
		return this.dcItmSls;
	}

	public void setDcItmSls(Date dcItmSls) {
		this.dcItmSls = dcItmSls;
	}

	@Column(name = "SC_ITM_SLS", length = 2)
	public String getScItmSls() {
		return this.scItmSls;
	}

	public void setScItmSls(String scItmSls) {
		this.scItmSls = scItmSls;
	}

	@Column(name = "RP_PRC_CMPR_AT_SLS", precision = 8)
	public BigDecimal getRpPrcCmprAtSls() {
		return this.rpPrcCmprAtSls;
	}

	public void setRpPrcCmprAtSls(BigDecimal rpPrcCmprAtSls) {
		this.rpPrcCmprAtSls = rpPrcCmprAtSls;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DC_PRC_MF_REC_RT", length = 7)
	public Date getDcPrcMfRecRt() {
		return this.dcPrcMfRecRt;
	}

	public void setDcPrcMfRecRt(Date dcPrcMfRecRt) {
		this.dcPrcMfRecRt = dcPrcMfRecRt;
	}

	@Column(name = "RP_PRC_MF_REC_RT", precision = 8)
	public BigDecimal getRpPrcMfRecRt() {
		return this.rpPrcMfRecRt;
	}

	public void setRpPrcMfRecRt(BigDecimal rpPrcMfRecRt) {
		this.rpPrcMfRecRt = rpPrcMfRecRt;
	}

	@Column(name = "ID_GP_TX", precision = 22, scale = 0)
	public BigDecimal getIdGpTx() {
		return this.idGpTx;
	}

	public void setIdGpTx(BigDecimal idGpTx) {
		this.idGpTx = idGpTx;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DC_PRC_SLS_EP_CRT", length = 7)
	public Date getDcPrcSlsEpCrt() {
		return this.dcPrcSlsEpCrt;
	}

	public void setDcPrcSlsEpCrt(Date dcPrcSlsEpCrt) {
		this.dcPrcSlsEpCrt = dcPrcSlsEpCrt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DC_PRC_SLS_EF_CRT", length = 7)
	public Date getDcPrcSlsEfCrt() {
		return this.dcPrcSlsEfCrt;
	}

	public void setDcPrcSlsEfCrt(Date dcPrcSlsEfCrt) {
		this.dcPrcSlsEfCrt = dcPrcSlsEfCrt;
	}

	@Column(name = "FL_PRC_RT_PNT_ALW", length = 1)
	public Character getFlPrcRtPntAlw() {
		return this.flPrcRtPntAlw;
	}

	public void setFlPrcRtPntAlw(Character flPrcRtPntAlw) {
		this.flPrcRtPntAlw = flPrcRtPntAlw;
	}

	@Column(name = "TY_PRC_RT", length = 2)
	public String getTyPrcRt() {
		return this.tyPrcRt;
	}

	public void setTyPrcRt(String tyPrcRt) {
		this.tyPrcRt = tyPrcRt;
	}

	@Column(name = "RP_SLS_CRT", precision = 8)
	public BigDecimal getRpSlsCrt() {
		return this.rpSlsCrt;
	}

	public void setRpSlsCrt(BigDecimal rpSlsCrt) {
		this.rpSlsCrt = rpSlsCrt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DC_PRC_EF_PRN_RT", length = 7)
	public Date getDcPrcEfPrnRt() {
		return this.dcPrcEfPrnRt;
	}

	public void setDcPrcEfPrnRt(Date dcPrcEfPrnRt) {
		this.dcPrcEfPrnRt = dcPrcEfPrnRt;
	}

	@Column(name = "QU_MKD_PR_PRC_PR", precision = 7, scale = 3)
	public BigDecimal getQuMkdPrPrcPr() {
		return this.quMkdPrPrcPr;
	}

	public void setQuMkdPrPrcPr(BigDecimal quMkdPrPrcPr) {
		this.quMkdPrPrcPr = quMkdPrPrcPr;
	}

	@Column(name = "FL_MKD_ORGL_PRC_PR", length = 1)
	public Character getFlMkdOrglPrcPr() {
		return this.flMkdOrglPrcPr;
	}

	public void setFlMkdOrglPrcPr(Character flMkdOrglPrcPr) {
		this.flMkdOrglPrcPr = flMkdOrglPrcPr;
	}

	@Column(name = "RP_PR_SLS", precision = 8)
	public BigDecimal getRpPrSls() {
		return this.rpPrSls;
	}

	public void setRpPrSls(BigDecimal rpPrSls) {
		this.rpPrSls = rpPrSls;
	}

	@Column(name = "SC_ITM", length = 2)
	public String getScItm() {
		return this.scItm;
	}

	public void setScItm(String scItm) {
		this.scItm = scItm;
	}

	@Column(name = "IDN_SLS_AG_RST", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdnSlsAgRst() {
		return this.idnSlsAgRst;
	}

	public void setIdnSlsAgRst(BigDecimal idnSlsAgRst) {
		this.idnSlsAgRst = idnSlsAgRst;
	}

	@Column(name = "ID_TMPLT_LB", length = 8)
	public String getIdTmpltLb() {
		return this.idTmpltLb;
	}

	public void setIdTmpltLb(String idTmpltLb) {
		this.idTmpltLb = idTmpltLb;
	}

	@Column(name = "TS_CRT_RCRD")
	public Serializable getTsCrtRcrd() {
		return this.tsCrtRcrd;
	}

	public void setTsCrtRcrd(Serializable tsCrtRcrd) {
		this.tsCrtRcrd = tsCrtRcrd;
	}

	@Column(name = "TS_MDF_RCRD")
	public Serializable getTsMdfRcrd() {
		return this.tsMdfRcrd;
	}

	public void setTsMdfRcrd(Serializable tsMdfRcrd) {
		this.tsMdfRcrd = tsMdfRcrd;
	}

	@Column(name = "SSL_BIZ_FRMT", length = 20)
	public String getSslBizFrmt() {
		return this.sslBizFrmt;
	}

	public void setSslBizFrmt(String sslBizFrmt) {
		this.sslBizFrmt = sslBizFrmt;
	}

	@Column(name = "PRC_MXM_RT", length = 20)
	public String getPrcMxmRt() {
		return this.prcMxmRt;
	}

	public void setPrcMxmRt(String prcMxmRt) {
		this.prcMxmRt = prcMxmRt;
	}

}
