package com.ssl.inbound.rest.db.beans;

// Generated Feb 20, 2017 5:28:35 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AsItm generated by hbm2java
 */
@Entity
@Table(name = "AS_ITM")
public class AsItm implements java.io.Serializable {

	private String idItm;
	private String idItmPdt;
	private Character flItmDsc;
	private Character flItmDscDmg;
	private Character flAdtItmPrc;
	private Character flItmSzReq;
	private String idDptPos;
	private Character flAznFrSls;
	private String luExmTx;
	private String luItmUsg;
	private String nmItm;
	private String deItm;
	private String deItmShrt;
	private String tyItm;
	private String luKtSt;
	private Character flItmSbstIdn;
	private String luClnOrd;
	private BigDecimal idStrcMr;
	private BigDecimal idLnPrc;
	private String nmBrn;
	private String luSn;
	private String fy;
	private String luHrcMrLv;
	private String luSbsn;
	private BigDecimal idGpTx;
	private Character flActvnRq;
	private Character flItmRgstry;
	private String idMrhrcGp;
	private BigDecimal idMf;
	private Serializable tsCrtRcrd;
	private Serializable tsMdfRcrd;
	private String flMrpMu;
	private String idStrcMrCd0;
	private String idStrcMrCd1;
	private String idStrcMrCd2;
	private String idStrcMrCd3;
	private String idStrcMrCd4;
	private String idStrcMrCd5;
	private String idStrcMrCd6;
	private String idStrcMrCd7;
	private String idStrcMrCd8;
	private String idStrcMrCd9;

	public AsItm() {
	}

	public AsItm(String idItm) {
		this.idItm = idItm;
	}

	public AsItm(String idItm, String idItmPdt, Character flItmDsc,
			Character flItmDscDmg, Character flAdtItmPrc, Character flItmSzReq,
			String idDptPos, Character flAznFrSls, String luExmTx,
			String luItmUsg, String nmItm, String deItm, String deItmShrt,
			String tyItm, String luKtSt, Character flItmSbstIdn,
			String luClnOrd, BigDecimal idStrcMr, BigDecimal idLnPrc,
			String nmBrn, String luSn, String fy, String luHrcMrLv,
			String luSbsn, BigDecimal idGpTx, Character flActvnRq,
			Character flItmRgstry, String idMrhrcGp, BigDecimal idMf,
			Serializable tsCrtRcrd, Serializable tsMdfRcrd, String flMrpMu,
			String idStrcMrCd0, String idStrcMrCd1, String idStrcMrCd2,
			String idStrcMrCd3, String idStrcMrCd4, String idStrcMrCd5,
			String idStrcMrCd6, String idStrcMrCd7, String idStrcMrCd8,
			String idStrcMrCd9) {
		this.idItm = idItm;
		this.idItmPdt = idItmPdt;
		this.flItmDsc = flItmDsc;
		this.flItmDscDmg = flItmDscDmg;
		this.flAdtItmPrc = flAdtItmPrc;
		this.flItmSzReq = flItmSzReq;
		this.idDptPos = idDptPos;
		this.flAznFrSls = flAznFrSls;
		this.luExmTx = luExmTx;
		this.luItmUsg = luItmUsg;
		this.nmItm = nmItm;
		this.deItm = deItm;
		this.deItmShrt = deItmShrt;
		this.tyItm = tyItm;
		this.luKtSt = luKtSt;
		this.flItmSbstIdn = flItmSbstIdn;
		this.luClnOrd = luClnOrd;
		this.idStrcMr = idStrcMr;
		this.idLnPrc = idLnPrc;
		this.nmBrn = nmBrn;
		this.luSn = luSn;
		this.fy = fy;
		this.luHrcMrLv = luHrcMrLv;
		this.luSbsn = luSbsn;
		this.idGpTx = idGpTx;
		this.flActvnRq = flActvnRq;
		this.flItmRgstry = flItmRgstry;
		this.idMrhrcGp = idMrhrcGp;
		this.idMf = idMf;
		this.tsCrtRcrd = tsCrtRcrd;
		this.tsMdfRcrd = tsMdfRcrd;
		this.flMrpMu = flMrpMu;
		this.idStrcMrCd0 = idStrcMrCd0;
		this.idStrcMrCd1 = idStrcMrCd1;
		this.idStrcMrCd2 = idStrcMrCd2;
		this.idStrcMrCd3 = idStrcMrCd3;
		this.idStrcMrCd4 = idStrcMrCd4;
		this.idStrcMrCd5 = idStrcMrCd5;
		this.idStrcMrCd6 = idStrcMrCd6;
		this.idStrcMrCd7 = idStrcMrCd7;
		this.idStrcMrCd8 = idStrcMrCd8;
		this.idStrcMrCd9 = idStrcMrCd9;
	}

	@Id
	@Column(name = "ID_ITM", unique = true, nullable = false, length = 14)
	public String getIdItm() {
		return this.idItm;
	}

	public void setIdItm(String idItm) {
		this.idItm = idItm;
	}

	@Column(name = "ID_ITM_PDT", length = 14)
	public String getIdItmPdt() {
		return this.idItmPdt;
	}

	public void setIdItmPdt(String idItmPdt) {
		this.idItmPdt = idItmPdt;
	}

	@Column(name = "FL_ITM_DSC", length = 1)
	public Character getFlItmDsc() {
		return this.flItmDsc;
	}

	public void setFlItmDsc(Character flItmDsc) {
		this.flItmDsc = flItmDsc;
	}

	@Column(name = "FL_ITM_DSC_DMG", length = 1)
	public Character getFlItmDscDmg() {
		return this.flItmDscDmg;
	}

	public void setFlItmDscDmg(Character flItmDscDmg) {
		this.flItmDscDmg = flItmDscDmg;
	}

	@Column(name = "FL_ADT_ITM_PRC", length = 1)
	public Character getFlAdtItmPrc() {
		return this.flAdtItmPrc;
	}

	public void setFlAdtItmPrc(Character flAdtItmPrc) {
		this.flAdtItmPrc = flAdtItmPrc;
	}

	@Column(name = "FL_ITM_SZ_REQ", length = 1)
	public Character getFlItmSzReq() {
		return this.flItmSzReq;
	}

	public void setFlItmSzReq(Character flItmSzReq) {
		this.flItmSzReq = flItmSzReq;
	}

	@Column(name = "ID_DPT_POS", length = 14)
	public String getIdDptPos() {
		return this.idDptPos;
	}

	public void setIdDptPos(String idDptPos) {
		this.idDptPos = idDptPos;
	}

	@Column(name = "FL_AZN_FR_SLS", length = 1)
	public Character getFlAznFrSls() {
		return this.flAznFrSls;
	}

	public void setFlAznFrSls(Character flAznFrSls) {
		this.flAznFrSls = flAznFrSls;
	}

	@Column(name = "LU_EXM_TX", length = 20)
	public String getLuExmTx() {
		return this.luExmTx;
	}

	public void setLuExmTx(String luExmTx) {
		this.luExmTx = luExmTx;
	}

	@Column(name = "LU_ITM_USG", length = 20)
	public String getLuItmUsg() {
		return this.luItmUsg;
	}

	public void setLuItmUsg(String luItmUsg) {
		this.luItmUsg = luItmUsg;
	}

	@Column(name = "NM_ITM", length = 120)
	public String getNmItm() {
		return this.nmItm;
	}

	public void setNmItm(String nmItm) {
		this.nmItm = nmItm;
	}

	@Column(name = "DE_ITM", length = 250)
	public String getDeItm() {
		return this.deItm;
	}

	public void setDeItm(String deItm) {
		this.deItm = deItm;
	}

	@Column(name = "DE_ITM_SHRT", length = 120)
	public String getDeItmShrt() {
		return this.deItmShrt;
	}

	public void setDeItmShrt(String deItmShrt) {
		this.deItmShrt = deItmShrt;
	}

	@Column(name = "TY_ITM", length = 20)
	public String getTyItm() {
		return this.tyItm;
	}

	public void setTyItm(String tyItm) {
		this.tyItm = tyItm;
	}

	@Column(name = "LU_KT_ST", length = 20)
	public String getLuKtSt() {
		return this.luKtSt;
	}

	public void setLuKtSt(String luKtSt) {
		this.luKtSt = luKtSt;
	}

	@Column(name = "FL_ITM_SBST_IDN", length = 1)
	public Character getFlItmSbstIdn() {
		return this.flItmSbstIdn;
	}

	public void setFlItmSbstIdn(Character flItmSbstIdn) {
		this.flItmSbstIdn = flItmSbstIdn;
	}

	@Column(name = "LU_CLN_ORD", length = 20)
	public String getLuClnOrd() {
		return this.luClnOrd;
	}

	public void setLuClnOrd(String luClnOrd) {
		this.luClnOrd = luClnOrd;
	}

	@Column(name = "ID_STRC_MR", precision = 22, scale = 0)
	public BigDecimal getIdStrcMr() {
		return this.idStrcMr;
	}

	public void setIdStrcMr(BigDecimal idStrcMr) {
		this.idStrcMr = idStrcMr;
	}

	@Column(name = "ID_LN_PRC", precision = 22, scale = 0)
	public BigDecimal getIdLnPrc() {
		return this.idLnPrc;
	}

	public void setIdLnPrc(BigDecimal idLnPrc) {
		this.idLnPrc = idLnPrc;
	}

	@Column(name = "NM_BRN", length = 120)
	public String getNmBrn() {
		return this.nmBrn;
	}

	public void setNmBrn(String nmBrn) {
		this.nmBrn = nmBrn;
	}

	@Column(name = "LU_SN", length = 20)
	public String getLuSn() {
		return this.luSn;
	}

	public void setLuSn(String luSn) {
		this.luSn = luSn;
	}

	@Column(name = "FY", length = 4)
	public String getFy() {
		return this.fy;
	}

	public void setFy(String fy) {
		this.fy = fy;
	}

	@Column(name = "LU_HRC_MR_LV", length = 4)
	public String getLuHrcMrLv() {
		return this.luHrcMrLv;
	}

	public void setLuHrcMrLv(String luHrcMrLv) {
		this.luHrcMrLv = luHrcMrLv;
	}

	@Column(name = "LU_SBSN", length = 20)
	public String getLuSbsn() {
		return this.luSbsn;
	}

	public void setLuSbsn(String luSbsn) {
		this.luSbsn = luSbsn;
	}

	@Column(name = "ID_GP_TX", precision = 22, scale = 0)
	public BigDecimal getIdGpTx() {
		return this.idGpTx;
	}

	public void setIdGpTx(BigDecimal idGpTx) {
		this.idGpTx = idGpTx;
	}

	@Column(name = "FL_ACTVN_RQ", length = 1)
	public Character getFlActvnRq() {
		return this.flActvnRq;
	}

	public void setFlActvnRq(Character flActvnRq) {
		this.flActvnRq = flActvnRq;
	}

	@Column(name = "FL_ITM_RGSTRY", length = 1)
	public Character getFlItmRgstry() {
		return this.flItmRgstry;
	}

	public void setFlItmRgstry(Character flItmRgstry) {
		this.flItmRgstry = flItmRgstry;
	}

	@Column(name = "ID_MRHRC_GP", length = 14)
	public String getIdMrhrcGp() {
		return this.idMrhrcGp;
	}

	public void setIdMrhrcGp(String idMrhrcGp) {
		this.idMrhrcGp = idMrhrcGp;
	}

	@Column(name = "ID_MF", precision = 22, scale = 0)
	public BigDecimal getIdMf() {
		return this.idMf;
	}

	public void setIdMf(BigDecimal idMf) {
		this.idMf = idMf;
	}

	@Column(name = "TS_CRT_RCRD")
	public Serializable getTsCrtRcrd() {
		return this.tsCrtRcrd;
	}

	public void setTsCrtRcrd(Serializable tsCrtRcrd) {
		this.tsCrtRcrd = tsCrtRcrd;
	}

	@Column(name = "TS_MDF_RCRD")
	public Serializable getTsMdfRcrd() {
		return this.tsMdfRcrd;
	}

	public void setTsMdfRcrd(Serializable tsMdfRcrd) {
		this.tsMdfRcrd = tsMdfRcrd;
	}

	@Column(name = "FL_MRP_MU", length = 20)
	public String getFlMrpMu() {
		return this.flMrpMu;
	}

	public void setFlMrpMu(String flMrpMu) {
		this.flMrpMu = flMrpMu;
	}

	@Column(name = "ID_STRC_MR_CD0", length = 20)
	public String getIdStrcMrCd0() {
		return this.idStrcMrCd0;
	}

	public void setIdStrcMrCd0(String idStrcMrCd0) {
		this.idStrcMrCd0 = idStrcMrCd0;
	}

	@Column(name = "ID_STRC_MR_CD1", length = 20)
	public String getIdStrcMrCd1() {
		return this.idStrcMrCd1;
	}

	public void setIdStrcMrCd1(String idStrcMrCd1) {
		this.idStrcMrCd1 = idStrcMrCd1;
	}

	@Column(name = "ID_STRC_MR_CD2", length = 20)
	public String getIdStrcMrCd2() {
		return this.idStrcMrCd2;
	}

	public void setIdStrcMrCd2(String idStrcMrCd2) {
		this.idStrcMrCd2 = idStrcMrCd2;
	}

	@Column(name = "ID_STRC_MR_CD3", length = 20)
	public String getIdStrcMrCd3() {
		return this.idStrcMrCd3;
	}

	public void setIdStrcMrCd3(String idStrcMrCd3) {
		this.idStrcMrCd3 = idStrcMrCd3;
	}

	@Column(name = "ID_STRC_MR_CD4", length = 20)
	public String getIdStrcMrCd4() {
		return this.idStrcMrCd4;
	}

	public void setIdStrcMrCd4(String idStrcMrCd4) {
		this.idStrcMrCd4 = idStrcMrCd4;
	}

	@Column(name = "ID_STRC_MR_CD5", length = 20)
	public String getIdStrcMrCd5() {
		return this.idStrcMrCd5;
	}

	public void setIdStrcMrCd5(String idStrcMrCd5) {
		this.idStrcMrCd5 = idStrcMrCd5;
	}

	@Column(name = "ID_STRC_MR_CD6", length = 20)
	public String getIdStrcMrCd6() {
		return this.idStrcMrCd6;
	}

	public void setIdStrcMrCd6(String idStrcMrCd6) {
		this.idStrcMrCd6 = idStrcMrCd6;
	}

	@Column(name = "ID_STRC_MR_CD7", length = 20)
	public String getIdStrcMrCd7() {
		return this.idStrcMrCd7;
	}

	public void setIdStrcMrCd7(String idStrcMrCd7) {
		this.idStrcMrCd7 = idStrcMrCd7;
	}

	@Column(name = "ID_STRC_MR_CD8", length = 20)
	public String getIdStrcMrCd8() {
		return this.idStrcMrCd8;
	}

	public void setIdStrcMrCd8(String idStrcMrCd8) {
		this.idStrcMrCd8 = idStrcMrCd8;
	}

	@Column(name = "ID_STRC_MR_CD9", length = 20)
	public String getIdStrcMrCd9() {
		return this.idStrcMrCd9;
	}

	public void setIdStrcMrCd9(String idStrcMrCd9) {
		this.idStrcMrCd9 = idStrcMrCd9;
	}

}
