package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CoStylI8Id generated by hbm2java
 */
@Embeddable
public class CoStylI8Id implements java.io.Serializable {

	private String luStyl;
	private String lcl;

	public CoStylI8Id() {
	}

	public CoStylI8Id(String luStyl, String lcl) {
		this.luStyl = luStyl;
		this.lcl = lcl;
	}

	@Column(name = "LU_STYL", nullable = false, length = 4)
	public String getLuStyl() {
		return this.luStyl;
	}

	public void setLuStyl(String luStyl) {
		this.luStyl = luStyl;
	}

	@Column(name = "LCL", nullable = false, length = 10)
	public String getLcl() {
		return this.lcl;
	}

	public void setLcl(String lcl) {
		this.lcl = lcl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CoStylI8Id))
			return false;
		CoStylI8Id castOther = (CoStylI8Id) other;

		return ((this.getLuStyl() == castOther.getLuStyl()) || (this
				.getLuStyl() != null && castOther.getLuStyl() != null && this
				.getLuStyl().equals(castOther.getLuStyl())))
				&& ((this.getLcl() == castOther.getLcl()) || (this.getLcl() != null
						&& castOther.getLcl() != null && this.getLcl().equals(
						castOther.getLcl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLuStyl() == null ? 0 : this.getLuStyl().hashCode());
		result = 37 * result
				+ (getLcl() == null ? 0 : this.getLcl().hashCode());
		return result;
	}

}
