package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CoStyl generated by hbm2java
 */
@Entity
@Table(name = "CO_STYL")
public class CoStyl implements java.io.Serializable {

	private String luStyl;
	private String nmStyl;
	private String deStyl;
	private Serializable tsCrtRcrd;
	private Serializable tsMdfRcrd;

	public CoStyl() {
	}

	public CoStyl(String luStyl) {
		this.luStyl = luStyl;
	}

	public CoStyl(String luStyl, String nmStyl, String deStyl,
			Serializable tsCrtRcrd, Serializable tsMdfRcrd) {
		this.luStyl = luStyl;
		this.nmStyl = nmStyl;
		this.deStyl = deStyl;
		this.tsCrtRcrd = tsCrtRcrd;
		this.tsMdfRcrd = tsMdfRcrd;
	}

	@Id
	@Column(name = "LU_STYL", unique = true, nullable = false, length = 4)
	public String getLuStyl() {
		return this.luStyl;
	}

	public void setLuStyl(String luStyl) {
		this.luStyl = luStyl;
	}

	@Column(name = "NM_STYL", length = 120)
	public String getNmStyl() {
		return this.nmStyl;
	}

	public void setNmStyl(String nmStyl) {
		this.nmStyl = nmStyl;
	}

	@Column(name = "DE_STYL", length = 250)
	public String getDeStyl() {
		return this.deStyl;
	}

	public void setDeStyl(String deStyl) {
		this.deStyl = deStyl;
	}

	@Column(name = "TS_CRT_RCRD")
	public Serializable getTsCrtRcrd() {
		return this.tsCrtRcrd;
	}

	public void setTsCrtRcrd(Serializable tsCrtRcrd) {
		this.tsCrtRcrd = tsCrtRcrd;
	}

	@Column(name = "TS_MDF_RCRD")
	public Serializable getTsMdfRcrd() {
		return this.tsMdfRcrd;
	}

	public void setTsMdfRcrd(Serializable tsMdfRcrd) {
		this.tsMdfRcrd = tsMdfRcrd;
	}

}
