package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CoStylI8 generated by hbm2java
 */
@Entity
@Table(name = "CO_STYL_I8")
public class CoStylI8 implements java.io.Serializable {

	private CoStylI8Id id;
	private String nmStyl;
	private String deStyl;

	public CoStylI8() {
	}

	public CoStylI8(CoStylI8Id id) {
		this.id = id;
	}

	public CoStylI8(CoStylI8Id id, String nmStyl, String deStyl) {
		this.id = id;
		this.nmStyl = nmStyl;
		this.deStyl = deStyl;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "luStyl", column = @Column(name = "LU_STYL", nullable = false, length = 4)),
			@AttributeOverride(name = "lcl", column = @Column(name = "LCL", nullable = false, length = 10)) })
	public CoStylI8Id getId() {
		return this.id;
	}

	public void setId(CoStylI8Id id) {
		this.id = id;
	}

	@Column(name = "NM_STYL", length = 120)
	public String getNmStyl() {
		return this.nmStyl;
	}

	public void setNmStyl(String nmStyl) {
		this.nmStyl = nmStyl;
	}

	@Column(name = "DE_STYL", length = 250)
	public String getDeStyl() {
		return this.deStyl;
	}

	public void setDeStyl(String deStyl) {
		this.deStyl = deStyl;
	}

}
