package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IdIdnPs generated by hbm2java
 */
@Entity
@Table(name = "ID_IDN_PS")
public class IdIdnPs implements java.io.Serializable {

	private IdIdnPsId id;
	private String deItmPos;
	private BigDecimal rpSlsPosCrt;
	private Character flPntFqShprEl;
	private BigDecimal idMf;
	private String idItmMfUpc;
	private BigDecimal idAgntRtn;
	private Character flDscAfDscAlw;
	private String luVtPsCpn;
	private String dtEndPsCpnOfr;
	private BigDecimal quUnBlkMnm;
	private BigDecimal quUnBlkMxm;
	private Character flDscMrkBskAlw;
	private Character flDscCtAcntAlw;
	private Character flDscEmAlw;
	private Character flCpnAlwMulty;
	private Character flFdStpAlw;
	private Character flCpnElntc;
	private Character flCpnRst;
	private Character flEntrPrcRq;
	private Character flQrEnrWt;
	private Character flKyPrhQty;
	private Character flRtnPrh;
	private Character flItmGwy;
	private Character flItmWic;
	private Character flPrcVsVr;
	private Character flKyPrhRpt;
	private Character flSpoItm;
	private BigDecimal quPntFqShpr;
	private String luGpTndRst;
	private String fcFmyMf;
	private Character flMdfrRtPrc;
	private BigDecimal idPrm;
	private BigDecimal idPrmCmp;
	private BigDecimal idPrmCmpDtl;
	private Serializable tsCrtRcrd;
	private Serializable tsMdfRcrd;
	private String sslBizFrmt;

	public IdIdnPs() {
	}

	public IdIdnPs(IdIdnPsId id, BigDecimal idPrm, BigDecimal idPrmCmp,
			BigDecimal idPrmCmpDtl) {
		this.id = id;
		this.idPrm = idPrm;
		this.idPrmCmp = idPrmCmp;
		this.idPrmCmpDtl = idPrmCmpDtl;
	}

	public IdIdnPs(IdIdnPsId id, String deItmPos, BigDecimal rpSlsPosCrt,
			Character flPntFqShprEl, BigDecimal idMf, String idItmMfUpc,
			BigDecimal idAgntRtn, Character flDscAfDscAlw, String luVtPsCpn,
			String dtEndPsCpnOfr, BigDecimal quUnBlkMnm, BigDecimal quUnBlkMxm,
			Character flDscMrkBskAlw, Character flDscCtAcntAlw,
			Character flDscEmAlw, Character flCpnAlwMulty,
			Character flFdStpAlw, Character flCpnElntc, Character flCpnRst,
			Character flEntrPrcRq, Character flQrEnrWt, Character flKyPrhQty,
			Character flRtnPrh, Character flItmGwy, Character flItmWic,
			Character flPrcVsVr, Character flKyPrhRpt, Character flSpoItm,
			BigDecimal quPntFqShpr, String luGpTndRst, String fcFmyMf,
			Character flMdfrRtPrc, BigDecimal idPrm, BigDecimal idPrmCmp,
			BigDecimal idPrmCmpDtl, Serializable tsCrtRcrd,
			Serializable tsMdfRcrd, String sslBizFrmt) {
		this.id = id;
		this.deItmPos = deItmPos;
		this.rpSlsPosCrt = rpSlsPosCrt;
		this.flPntFqShprEl = flPntFqShprEl;
		this.idMf = idMf;
		this.idItmMfUpc = idItmMfUpc;
		this.idAgntRtn = idAgntRtn;
		this.flDscAfDscAlw = flDscAfDscAlw;
		this.luVtPsCpn = luVtPsCpn;
		this.dtEndPsCpnOfr = dtEndPsCpnOfr;
		this.quUnBlkMnm = quUnBlkMnm;
		this.quUnBlkMxm = quUnBlkMxm;
		this.flDscMrkBskAlw = flDscMrkBskAlw;
		this.flDscCtAcntAlw = flDscCtAcntAlw;
		this.flDscEmAlw = flDscEmAlw;
		this.flCpnAlwMulty = flCpnAlwMulty;
		this.flFdStpAlw = flFdStpAlw;
		this.flCpnElntc = flCpnElntc;
		this.flCpnRst = flCpnRst;
		this.flEntrPrcRq = flEntrPrcRq;
		this.flQrEnrWt = flQrEnrWt;
		this.flKyPrhQty = flKyPrhQty;
		this.flRtnPrh = flRtnPrh;
		this.flItmGwy = flItmGwy;
		this.flItmWic = flItmWic;
		this.flPrcVsVr = flPrcVsVr;
		this.flKyPrhRpt = flKyPrhRpt;
		this.flSpoItm = flSpoItm;
		this.quPntFqShpr = quPntFqShpr;
		this.luGpTndRst = luGpTndRst;
		this.fcFmyMf = fcFmyMf;
		this.flMdfrRtPrc = flMdfrRtPrc;
		this.idPrm = idPrm;
		this.idPrmCmp = idPrmCmp;
		this.idPrmCmpDtl = idPrmCmpDtl;
		this.tsCrtRcrd = tsCrtRcrd;
		this.tsMdfRcrd = tsMdfRcrd;
		this.sslBizFrmt = sslBizFrmt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idStrRt", column = @Column(name = "ID_STR_RT", nullable = false, length = 5)),
			@AttributeOverride(name = "idItmPos", column = @Column(name = "ID_ITM_POS", nullable = false, length = 14)),
			@AttributeOverride(name = "idItm", column = @Column(name = "ID_ITM", nullable = false, length = 14)) })
	public IdIdnPsId getId() {
		return this.id;
	}

	public void setId(IdIdnPsId id) {
		this.id = id;
	}

	@Column(name = "DE_ITM_POS", length = 250)
	public String getDeItmPos() {
		return this.deItmPos;
	}

	public void setDeItmPos(String deItmPos) {
		this.deItmPos = deItmPos;
	}

	@Column(name = "RP_SLS_POS_CRT", precision = 8)
	public BigDecimal getRpSlsPosCrt() {
		return this.rpSlsPosCrt;
	}

	public void setRpSlsPosCrt(BigDecimal rpSlsPosCrt) {
		this.rpSlsPosCrt = rpSlsPosCrt;
	}

	@Column(name = "FL_PNT_FQ_SHPR_EL", length = 1)
	public Character getFlPntFqShprEl() {
		return this.flPntFqShprEl;
	}

	public void setFlPntFqShprEl(Character flPntFqShprEl) {
		this.flPntFqShprEl = flPntFqShprEl;
	}

	@Column(name = "ID_MF", precision = 22, scale = 0)
	public BigDecimal getIdMf() {
		return this.idMf;
	}

	public void setIdMf(BigDecimal idMf) {
		this.idMf = idMf;
	}

	@Column(name = "ID_ITM_MF_UPC", length = 14)
	public String getIdItmMfUpc() {
		return this.idItmMfUpc;
	}

	public void setIdItmMfUpc(String idItmMfUpc) {
		this.idItmMfUpc = idItmMfUpc;
	}

	@Column(name = "ID_AGNT_RTN", precision = 22, scale = 0)
	public BigDecimal getIdAgntRtn() {
		return this.idAgntRtn;
	}

	public void setIdAgntRtn(BigDecimal idAgntRtn) {
		this.idAgntRtn = idAgntRtn;
	}

	@Column(name = "FL_DSC_AF_DSC_ALW", length = 1)
	public Character getFlDscAfDscAlw() {
		return this.flDscAfDscAlw;
	}

	public void setFlDscAfDscAlw(Character flDscAfDscAlw) {
		this.flDscAfDscAlw = flDscAfDscAlw;
	}

	@Column(name = "LU_VT_PS_CPN", length = 2)
	public String getLuVtPsCpn() {
		return this.luVtPsCpn;
	}

	public void setLuVtPsCpn(String luVtPsCpn) {
		this.luVtPsCpn = luVtPsCpn;
	}

	@Column(name = "DT_END_PS_CPN_OFR", length = 4)
	public String getDtEndPsCpnOfr() {
		return this.dtEndPsCpnOfr;
	}

	public void setDtEndPsCpnOfr(String dtEndPsCpnOfr) {
		this.dtEndPsCpnOfr = dtEndPsCpnOfr;
	}

	@Column(name = "QU_UN_BLK_MNM", precision = 5)
	public BigDecimal getQuUnBlkMnm() {
		return this.quUnBlkMnm;
	}

	public void setQuUnBlkMnm(BigDecimal quUnBlkMnm) {
		this.quUnBlkMnm = quUnBlkMnm;
	}

	@Column(name = "QU_UN_BLK_MXM", precision = 5)
	public BigDecimal getQuUnBlkMxm() {
		return this.quUnBlkMxm;
	}

	public void setQuUnBlkMxm(BigDecimal quUnBlkMxm) {
		this.quUnBlkMxm = quUnBlkMxm;
	}

	@Column(name = "FL_DSC_MRK_BSK_ALW", length = 1)
	public Character getFlDscMrkBskAlw() {
		return this.flDscMrkBskAlw;
	}

	public void setFlDscMrkBskAlw(Character flDscMrkBskAlw) {
		this.flDscMrkBskAlw = flDscMrkBskAlw;
	}

	@Column(name = "FL_DSC_CT_ACNT_ALW", length = 1)
	public Character getFlDscCtAcntAlw() {
		return this.flDscCtAcntAlw;
	}

	public void setFlDscCtAcntAlw(Character flDscCtAcntAlw) {
		this.flDscCtAcntAlw = flDscCtAcntAlw;
	}

	@Column(name = "FL_DSC_EM_ALW", length = 1)
	public Character getFlDscEmAlw() {
		return this.flDscEmAlw;
	}

	public void setFlDscEmAlw(Character flDscEmAlw) {
		this.flDscEmAlw = flDscEmAlw;
	}

	@Column(name = "FL_CPN_ALW_MULTY", length = 1)
	public Character getFlCpnAlwMulty() {
		return this.flCpnAlwMulty;
	}

	public void setFlCpnAlwMulty(Character flCpnAlwMulty) {
		this.flCpnAlwMulty = flCpnAlwMulty;
	}

	@Column(name = "FL_FD_STP_ALW", length = 1)
	public Character getFlFdStpAlw() {
		return this.flFdStpAlw;
	}

	public void setFlFdStpAlw(Character flFdStpAlw) {
		this.flFdStpAlw = flFdStpAlw;
	}

	@Column(name = "FL_CPN_ELNTC", length = 1)
	public Character getFlCpnElntc() {
		return this.flCpnElntc;
	}

	public void setFlCpnElntc(Character flCpnElntc) {
		this.flCpnElntc = flCpnElntc;
	}

	@Column(name = "FL_CPN_RST", length = 1)
	public Character getFlCpnRst() {
		return this.flCpnRst;
	}

	public void setFlCpnRst(Character flCpnRst) {
		this.flCpnRst = flCpnRst;
	}

	@Column(name = "FL_ENTR_PRC_RQ", length = 1)
	public Character getFlEntrPrcRq() {
		return this.flEntrPrcRq;
	}

	public void setFlEntrPrcRq(Character flEntrPrcRq) {
		this.flEntrPrcRq = flEntrPrcRq;
	}

	@Column(name = "FL_QR_ENR_WT", length = 1)
	public Character getFlQrEnrWt() {
		return this.flQrEnrWt;
	}

	public void setFlQrEnrWt(Character flQrEnrWt) {
		this.flQrEnrWt = flQrEnrWt;
	}

	@Column(name = "FL_KY_PRH_QTY", length = 1)
	public Character getFlKyPrhQty() {
		return this.flKyPrhQty;
	}

	public void setFlKyPrhQty(Character flKyPrhQty) {
		this.flKyPrhQty = flKyPrhQty;
	}

	@Column(name = "FL_RTN_PRH", length = 1)
	public Character getFlRtnPrh() {
		return this.flRtnPrh;
	}

	public void setFlRtnPrh(Character flRtnPrh) {
		this.flRtnPrh = flRtnPrh;
	}

	@Column(name = "FL_ITM_GWY", length = 1)
	public Character getFlItmGwy() {
		return this.flItmGwy;
	}

	public void setFlItmGwy(Character flItmGwy) {
		this.flItmGwy = flItmGwy;
	}

	@Column(name = "FL_ITM_WIC", length = 1)
	public Character getFlItmWic() {
		return this.flItmWic;
	}

	public void setFlItmWic(Character flItmWic) {
		this.flItmWic = flItmWic;
	}

	@Column(name = "FL_PRC_VS_VR", length = 1)
	public Character getFlPrcVsVr() {
		return this.flPrcVsVr;
	}

	public void setFlPrcVsVr(Character flPrcVsVr) {
		this.flPrcVsVr = flPrcVsVr;
	}

	@Column(name = "FL_KY_PRH_RPT", length = 1)
	public Character getFlKyPrhRpt() {
		return this.flKyPrhRpt;
	}

	public void setFlKyPrhRpt(Character flKyPrhRpt) {
		this.flKyPrhRpt = flKyPrhRpt;
	}

	@Column(name = "FL_SPO_ITM", length = 1)
	public Character getFlSpoItm() {
		return this.flSpoItm;
	}

	public void setFlSpoItm(Character flSpoItm) {
		this.flSpoItm = flSpoItm;
	}

	@Column(name = "QU_PNT_FQ_SHPR", precision = 9)
	public BigDecimal getQuPntFqShpr() {
		return this.quPntFqShpr;
	}

	public void setQuPntFqShpr(BigDecimal quPntFqShpr) {
		this.quPntFqShpr = quPntFqShpr;
	}

	@Column(name = "LU_GP_TND_RST", length = 20)
	public String getLuGpTndRst() {
		return this.luGpTndRst;
	}

	public void setLuGpTndRst(String luGpTndRst) {
		this.luGpTndRst = luGpTndRst;
	}

	@Column(name = "FC_FMY_MF", length = 3)
	public String getFcFmyMf() {
		return this.fcFmyMf;
	}

	public void setFcFmyMf(String fcFmyMf) {
		this.fcFmyMf = fcFmyMf;
	}

	@Column(name = "FL_MDFR_RT_PRC", length = 1)
	public Character getFlMdfrRtPrc() {
		return this.flMdfrRtPrc;
	}

	public void setFlMdfrRtPrc(Character flMdfrRtPrc) {
		this.flMdfrRtPrc = flMdfrRtPrc;
	}

	@Column(name = "ID_PRM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPrm() {
		return this.idPrm;
	}

	public void setIdPrm(BigDecimal idPrm) {
		this.idPrm = idPrm;
	}

	@Column(name = "ID_PRM_CMP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPrmCmp() {
		return this.idPrmCmp;
	}

	public void setIdPrmCmp(BigDecimal idPrmCmp) {
		this.idPrmCmp = idPrmCmp;
	}

	@Column(name = "ID_PRM_CMP_DTL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPrmCmpDtl() {
		return this.idPrmCmpDtl;
	}

	public void setIdPrmCmpDtl(BigDecimal idPrmCmpDtl) {
		this.idPrmCmpDtl = idPrmCmpDtl;
	}

	@Column(name = "TS_CRT_RCRD")
	public Serializable getTsCrtRcrd() {
		return this.tsCrtRcrd;
	}

	public void setTsCrtRcrd(Serializable tsCrtRcrd) {
		this.tsCrtRcrd = tsCrtRcrd;
	}

	@Column(name = "TS_MDF_RCRD")
	public Serializable getTsMdfRcrd() {
		return this.tsMdfRcrd;
	}

	public void setTsMdfRcrd(Serializable tsMdfRcrd) {
		this.tsMdfRcrd = tsMdfRcrd;
	}

	@Column(name = "SSL_BIZ_FRMT", length = 20)
	public String getSslBizFrmt() {
		return this.sslBizFrmt;
	}

	public void setSslBizFrmt(String sslBizFrmt) {
		this.sslBizFrmt = sslBizFrmt;
	}

}
