package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaPrty generated by hbm2java
 */
@Entity
@Table(name = "PA_PRTY")
public class PaPrty implements java.io.Serializable {

	private BigDecimal idPrty;
	private String luOrgLg;
	private String tyPrty;

	public PaPrty() {
	}

	public PaPrty(BigDecimal idPrty) {
		this.idPrty = idPrty;
	}

	public PaPrty(BigDecimal idPrty, String luOrgLg, String tyPrty) {
		this.idPrty = idPrty;
		this.luOrgLg = luOrgLg;
		this.tyPrty = tyPrty;
	}

	@Id
	@Column(name = "ID_PRTY", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPrty() {
		return this.idPrty;
	}

	public void setIdPrty(BigDecimal idPrty) {
		this.idPrty = idPrty;
	}

	@Column(name = "LU_ORG_LG", length = 20)
	public String getLuOrgLg() {
		return this.luOrgLg;
	}

	public void setLuOrgLg(String luOrgLg) {
		this.luOrgLg = luOrgLg;
	}

	@Column(name = "TY_PRTY", length = 20)
	public String getTyPrty() {
		return this.tyPrty;
	}

	public void setTyPrty(String tyPrty) {
		this.tyPrty = tyPrty;
	}

}
