package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaSpr generated by hbm2java
 */
@Entity
@Table(name = "PA_SPR")
public class PaSpr implements java.io.Serializable {

	private String idSpr;
	private String duSpr;
	private String nmSpr;
	private BigDecimal idPrty;
	private String tyRoPrty;
	private Character flMfSprIs;

	public PaSpr() {
	}

	public PaSpr(String idSpr) {
		this.idSpr = idSpr;
	}

	public PaSpr(String idSpr, String duSpr, String nmSpr, BigDecimal idPrty,
			String tyRoPrty, Character flMfSprIs) {
		this.idSpr = idSpr;
		this.duSpr = duSpr;
		this.nmSpr = nmSpr;
		this.idPrty = idPrty;
		this.tyRoPrty = tyRoPrty;
		this.flMfSprIs = flMfSprIs;
	}

	@Id
	@Column(name = "ID_SPR", unique = true, nullable = false, length = 20)
	public String getIdSpr() {
		return this.idSpr;
	}

	public void setIdSpr(String idSpr) {
		this.idSpr = idSpr;
	}

	@Column(name = "DU_SPR", length = 9)
	public String getDuSpr() {
		return this.duSpr;
	}

	public void setDuSpr(String duSpr) {
		this.duSpr = duSpr;
	}

	@Column(name = "NM_SPR", length = 120)
	public String getNmSpr() {
		return this.nmSpr;
	}

	public void setNmSpr(String nmSpr) {
		this.nmSpr = nmSpr;
	}

	@Column(name = "ID_PRTY", precision = 22, scale = 0)
	public BigDecimal getIdPrty() {
		return this.idPrty;
	}

	public void setIdPrty(BigDecimal idPrty) {
		this.idPrty = idPrty;
	}

	@Column(name = "TY_RO_PRTY", length = 20)
	public String getTyRoPrty() {
		return this.tyRoPrty;
	}

	public void setTyRoPrty(String tyRoPrty) {
		this.tyRoPrty = tyRoPrty;
	}

	@Column(name = "FL_MF_SPR_IS", length = 1)
	public Character getFlMfSprIs() {
		return this.flMfSprIs;
	}

	public void setFlMfSprIs(Character flMfSprIs) {
		this.flMfSprIs = flMfSprIs;
	}

}
