package com.ssl.inbound.rest.db.beans;

// Generated Feb 18, 2017 6:19:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaSprI8Id generated by hbm2java
 */
@Embeddable
public class PaSprI8Id implements java.io.Serializable {

	private String idSpr;
	private String lcl;

	public PaSprI8Id() {
	}

	public PaSprI8Id(String idSpr, String lcl) {
		this.idSpr = idSpr;
		this.lcl = lcl;
	}

	@Column(name = "ID_SPR", nullable = false, length = 20)
	public String getIdSpr() {
		return this.idSpr;
	}

	public void setIdSpr(String idSpr) {
		this.idSpr = idSpr;
	}

	@Column(name = "LCL", nullable = false, length = 10)
	public String getLcl() {
		return this.lcl;
	}

	public void setLcl(String lcl) {
		this.lcl = lcl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaSprI8Id))
			return false;
		PaSprI8Id castOther = (PaSprI8Id) other;

		return ((this.getIdSpr() == castOther.getIdSpr()) || (this.getIdSpr() != null
				&& castOther.getIdSpr() != null && this.getIdSpr().equals(
				castOther.getIdSpr())))
				&& ((this.getLcl() == castOther.getLcl()) || (this.getLcl() != null
						&& castOther.getLcl() != null && this.getLcl().equals(
						castOther.getLcl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdSpr() == null ? 0 : this.getIdSpr().hashCode());
		result = 37 * result
				+ (getLcl() == null ? 0 : this.getLcl().hashCode());
		return result;
	}

}
