/**
 * 
 */
package com.ssl.inbound.rest.sqlIfc;

/**
 * @author Srikanth
 *
 */
public interface ItemUpdateSQLIfc 
{

	String AS_ITM_Insert = "INSERT INTO AS_ITM (ID_ITM,ID_ITM_PDT,FL_ITM_DSC,FL_ITM_DSC_DMG,FL_ADT_ITM_PRC,FL_ITM_SZ_REQ,ID_DPT_POS,FL_AZN_FR_SLS,LU_EXM_TX,"+
			" LU_ITM_USG,NM_ITM,DE_ITM,DE_ITM_SHRT,TY_ITM,LU_KT_ST,FL_ITM_SBST_IDN,LU_CLN_ORD,ID_STRC_MR,ID_LN_PRC,NM_BRN,LU_SN,FY,LU_HRC_MR_LV,LU_SBSN,ID_GP_TX,"+
			" FL_ACTVN_RQ,FL_ITM_RGSTRY,ID_STRC_MR_CD0,ID_STRC_MR_CD1,ID_STRC_MR_CD2,ID_STRC_MR_CD3,ID_STRC_MR_CD4,ID_STRC_MR_CD5,ID_STRC_MR_CD6,ID_STRC_MR_CD7, "+
			" ID_STRC_MR_CD8,ID_STRC_MR_CD9,ID_MRHRC_GP,ID_MF,TS_CRT_RCRD,TS_MDF_RCRD,FL_MRP_MU) "+
			" 	VALUES( "+
			" 	?,"+
			" 	?,"+
			" 	DECODE(?,'Y',1,0),"+
			" 	'1',"+
			" 	NULL,"+
			" 	'0',"+
			" 	RPAD(LPAD(?,3,0)||LPAD(?,3,0),12,0),"+
			" 	'1',"+
			" 	'1',"+
			" 	NULL,"+
			" 	?,"+
			" 	UPPER(?),"+
			" 	?,"+
			" 	?,"+
			" 	DECODE(?,'Y','1','0'), "+
			" 	'0',"+
			" 	NULL,"+
			" 	-1,"+
			" 	NULL,"+
			" 	?,"+
			" 	?,"+
			" 	NULL,"+
			" 	?,"+
			" 	NULL,"+
			" 	2,"+
			" 	'0',"+
			" 	'1',"+
			"   NULL,"+
			"   NULL,"+
			"   NULL,"+
			"   NULL, "+
			"   NULL,"+
			" 	NULL,"+
			" 	NULL,"+
			" 	NULL,"+
			" 	NULL,"+
			" 	NULL,"+
			" 	RPAD(LPAD(?,3,0)||LPAD(?,3,0)||LPAD(?,3,0)||LPAD(?,3,0),12,0),"+ 
			" 	NULL,"+
			" 	SYSDATE,"+
			" 	SYSDATE,"+
			" 	DECODE(?,'Y',1,0))";
	
	String AS_ITM_I8_Insert = "INSERT INTO AS_ITM_I8 (ID_ITM,LCL,DE_ITM,NM_ITM,DE_ITM_SHRT,NM_BRN) "
			+ "VALUES("
			+ "?,"
			+ "'en',"
			+ "?,"
			+ "?,"
			+ "?,"
			+ "NULL)";
	
	String AS_ITM_STK_Insert = "INSERT INTO AS_ITM_STK (ID_ITM,LU_UOM_SLS,ED_CLR,ED_SZ,LU_STYL,ID_STR_RT,QL_HT_PCKG_CNS,ID_SPR,NM_NMB_SRZ_ITM_MDL,QL_UOM_WD_PCKG_CNS, "
			+ " TY_WST_BLK_SLS,CY_MDL_SRZ_ITM,QU_CPC_HLD,LU_UOM,QW_ITM_PCK,TY_UN_DPLY,QU_CB_PCK_ITM,QL_PCKG_CNS,DE_CLR_MF_SRZ_ITM,TY_ITM_STK,PE_WST_BLK_SLS,	LU_UOM_PCKG_CNS_DMN,"
			+ " LU_SYS_PRMRY_MS,DE_SZ_MF_SRZ_ITM,QU_UN_PCK_ITM,DC_UN_DPLY_ST_UP,LU_WRTY_MF_SRZ_ITM,QW_WT_PCKG_CNS,DC_UN_DPLY_TK_DWN,DE_FBRC,DP_UN_DPLY,LU_CNT_SLS_WT_UN,"
			+ " LU_WRTY_STR_SRZ,LU_UOM_WT_PCKG_CNS,TY_PKP_CT_STK_ITM,LU_UOM_SZ_PCKG_CNS,DE_SLH,FL_VLD_SRZ_ITM,TY_SRZ_ITM,ID_SRZ_ITM_LB,CD_SRZ_CPT_TM,FL_SRZ_CRT_EXT,"
			+ " FA_PRC_UN_STK_ITM,FL_DSD_AZN,DI_PRD_SH_LF,DI_LF_SH,ID_BRKR,DC_AVLB_FR_SLS,TY_ITM_STPL_PRSH,TY_ENV_STK_ITM,NM_LCN_ASL,TY_SCTY_RQ,NM_LCN_SH,NM_LCN_SID,"
			+ " TY_MTR_HZ_STK_ITM,QU_FCG,CP_UN_SL_LS_RCV_BS,CP_CST_NT_LS_RCV,CP_UN_SL_LND,DC_CST_EST_LS_RCV,FL_SHRK_SH_ITM,FL_SWL_SH_ITM,FL_RQ_UN_PRC,FL_FE_RSTK,"
			+ " TS_CRT_RCRD,TS_MDF_RCRD)"
			+ " VALUES("
			+ " ?,"
			+ " ?,"
			+ " ?,"
			+ " ?,"
			+ " ?,"
			+ " LPAD(?,5,0),"
			+ " 0,"
			+ " ?,"
			+ " NULL,0,NULL,NULL,0,NULL,0,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"
			+ " DECODE(?,'Y',1,0),"
			+ " NULL,NULL,'SALE','1',0,NULL,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL,NULL,NULL,NULL,'0',SYSDATE,SYSDATE)";
	
	String AS_ITM_RTL_STR_Insert = "INSERT INTO AS_ITM_RTL_STR (ID_STR_RT,ID_ITM,FL_STK_UPT_ON_HD,DC_ITM_SLS,SC_ITM_SLS,RP_PRC_CMPR_AT_SLS,DC_PRC_MF_REC_RT, "
			+ " RP_PRC_MF_REC_RT,ID_GP_TX,DC_PRC_SLS_EP_CRT,DC_PRC_SLS_EF_CRT,FL_PRC_RT_PNT_ALW,TY_PRC_RT,RP_SLS_CRT,DC_PRC_EF_PRN_RT,QU_MKD_PR_PRC_PR,FL_MKD_ORGL_PRC_PR,"
			+ " RP_PR_SLS,SC_ITM,IDN_SLS_AG_RST,ID_TMPLT_LB,TS_CRT_RCRD,TS_MDF_RCRD,SSL_BIZ_FRMT,PRC_MXM_RT)"
			+ " VALUES("
			+ " LPAD(?,5,0),"
			+ " ?,"
			+ " NULL,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'SALTEMPL', SYSDATE,SYSDATE,"
			+ " ?,"
			+ " ?)";
	
	String AS_ITM_SPR_Insert = "INSERT INTO AS_ITM_SPR (ID_SPR,ID_ITM_SPR,ID_ITM_MF_UPC,TS_CRT_RCRD,TS_MDF_RCRD)"
			+ " VALUES("
			+ " ?,"
			+ " ?,"
			+ " ?,"
			+ " SYSDATE,SYSDATE)";
	
	String DO_MSG_SEQ_Select = "SELECT ID_MSG_SEQ.NEXTVAL AS MSG_SEQ FROM DUAL";
	
	String DO_MSG_Insert = "INSERT INTO DO_MSG (ID_MSG) VALUES (?)";
	
	String DO_MSG_I8_Insert = "INSERT INTO DO_MSG_I8 (ID_MSG,LCL,NM_MSG_DPLY,NA_MSG_DPLY) "
			+ "VALUES("
			+ "?,"
			+ "'en',"
			+ "?,"
			+ "?)";
	
	String AS_ITM_ASCTN_MSG_Insert = "INSERT INTO AS_ITM_ASCTN_MSG (ID_ITM,ID_MSG,TY_TRN_USG,TY_DPLY_LOC)"
			+ "	VALUES ("
			+ " ?,"
			+ " ?,"
			+ " ?,"
			+ " ?)";
	
	String ID_IDN_PS_Insert = "INSERT INTO ID_IDN_PS (ID_STR_RT,ID_ITM_POS,ID_ITM,DE_ITM_POS,RP_SLS_POS_CRT,FL_PNT_FQ_SHPR_EL,ID_MF,ID_ITM_MF_UPC,ID_AGNT_RTN, "
			+ " FL_DSC_AF_DSC_ALW,LU_VT_PS_CPN,DT_END_PS_CPN_OFR,QU_UN_BLK_MNM,QU_UN_BLK_MXM,FL_DSC_MRK_BSK_ALW,FL_DSC_CT_ACNT_ALW,FL_DSC_EM_ALW,FL_CPN_ALW_MULTY,"
			+ " FL_FD_STP_ALW,FL_CPN_ELNTC,FL_CPN_RST,FL_ENTR_PRC_RQ,FL_QR_ENR_WT,FL_KY_PRH_QTY,FL_RTN_PRH,FL_ITM_GWY,FL_ITM_WIC,FL_PRC_VS_VR,FL_KY_PRH_RPT,"
			+ " FL_SPO_ITM,QU_PNT_FQ_SHPR,LU_GP_TND_RST,FC_FMY_MF,FL_MDFR_RT_PRC,ID_PRM,ID_PRM_CMP,ID_PRM_CMP_DTL,TS_CRT_RCRD,TS_MDF_RCRD,SSL_BIZ_FRMT)"
			+ " VALUES("
			+ " LPAD(?,5,0),"
			+ " ?,"
			+ " ?,"
			+ " ?,"
			+ " NULL,NULL,0,NULL,0,NULL,'00',NULL,1,-1,NULL,NULL,"
			+ " DECODE(?,'Y',1,0)," //17 : FL_DSC_EM_ALW
			+ " '0',NULL,'0','0',"
			+ " DECODE(?,'Y','1','0')," //22 : FL_ENTR_PRC_RQ
			+ " NULL,'0','0',NULL,NULL,NULL,NULL,'1',0,NULL,NULL,"
			+ " DECODE(?,'Y',1,0), " // FL_MDFR_RT_PRC
			+ " 0,0,0,SYSDATE,SYSDATE,"
			+ " ?)";
	
	String CO_BRK_SPR_ITM_BS_Insert = "INSERT INTO CO_BRK_SPR_ITM_BS (ID_SPR,ID_ITM_SPR,TY_UN_CST,QU_PNT_UND_BRK,CP_PNT_BRK_BS_CST,TS_CRT_RCRD,TS_MDF_RCRD) "
			+ "	VALUES("
			+ " ?,"
			+ " ?,"
			+ "'SLU',0,0.16,SYSDATE,SYSDATE)";
}
